In [40]:
import numpy as np
r = np.array([[0,0,0],[0,1,2],[0,2,2]])
w0 = np.array([[0,0,0],[1,0,-1],[1,1,1]])

g = np.array([[0,0,0],[0,1,2],[0,2,2]])
w1 = np.array([[1,1,1],[0,-1,0],[1,-1,1]])

b = np.array([[0,0,0],[0,2,2],[0,1,2]])
w2 = np.array([[-1,0,1],[-1,1,-1],[0,0,1]])


# r.dot(w0).sum() + b.dot(w1).sum() + b.dot(w2).sum()
print((r * w0).sum())
print((g * w1).sum())
print((b * w2).sum())

2
-1
2


In [8]:
import numpy 
a = numpy.arange(3*3).reshape(3,3)
b = numpy.arange(3*3).reshape(3,3)
print(a)
print(b)
print(a.dot(b))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]
