# Basic Numpy array

In [2]:
import numpy as np

In [17]:
b = np.array([6, 7, 8])
print(b)
print(type(b))

[6 7 8]
<class 'numpy.ndarray'>


In [5]:
a = np.arange(15)
a
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
print(type(a))
print("a.shape\t", a.shape)
print("a.ndim\t", a.ndim)
print("a.dtype.name\t", a.dtype.name)
print("a.itemsize\t", a.itemsize)
print("a.size\t", a.size)

<class 'numpy.ndarray'>
a.shape	 (3, 5)
a.ndim	 2
a.dtype.name	 int64
a.itemsize	 8
a.size	 15


In [18]:
b = np.array([(1.5,2,3), (4,5,6)])
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [19]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
print(c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


## Array Creation

In [22]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.ones( (2,3,4), dtype=np.int16 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [31]:
np.empty( (2,3), dtype=np.float32 )  

array([[8.4e-45, 0.0e+00, 9.8e-45],
       [0.0e+00, 1.1e-44, 0.0e+00]], dtype=float32)

In [34]:
np.arange( 10, 30, 3 )

array([10, 13, 16, 19, 22, 25, 28])

In [35]:
np.arange( 0, 2, 0.3 ) 

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [39]:
np.linspace( 0, 8, 9 )  

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

## Array Operations

In [44]:
a = np.array([20,30,40,50])
b = np.arange(4)
print(b)

[0 1 2 3]


In [45]:
c = a + b
print(c)

[20 31 42 53]


In [46]:
b ** 2

array([0, 1, 4, 9])

In [47]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [48]:
a < 35

array([ True,  True, False, False])

In [5]:
A = np.array( [[1,1], [0,1]] )
B = np.array( [[2,0], [3,4]] )

A * B

array([[2, 0],
       [0, 4]])

In [6]:
A @ B

array([[5, 4],
       [3, 4]])

In [8]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [9]:
b += a
b

array([[3.17028449, 3.20381802, 3.21547188],
       [3.83381064, 3.07179061, 3.87324439]])

In [13]:
a = np.random.random((2,3,4))
a.sum()

12.240747845149476

In [14]:
a.min()

0.00872689159727269

In [15]:
a.max()

0.9819630472916975

[[[0.4519226  0.12617974 0.41365575 0.7064321 ]
  [0.24369552 0.83549567 0.52259112 0.91802668]
  [0.85277407 0.03634609 0.17641448 0.57852025]]

 [[0.33436822 0.63124229 0.34143616 0.30976195]
  [0.85082186 0.57084868 0.41294702 0.25309954]
  [0.01079821 0.80836706 0.17646198 0.849574  ]]]


array([[0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 1, 1]])

In [41]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
b.sum(axis=0) 

array([12, 15, 18, 21])

In [45]:
b.sum(axis=1) 


array([ 6, 22, 38])

In [46]:
b.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [50]:
a = np.random.random((2,3,4))
print(a)
print(a.argmax(axis=0))
print(a.argmax(axis=1))

[[[0.53218484 0.18332522 0.98307585 0.79444394]
  [0.0063191  0.39546128 0.52609408 0.90645197]
  [0.46602074 0.72157016 0.85787836 0.32342206]]

 [[0.7895007  0.36797402 0.17054819 0.84846403]
  [0.66995055 0.11005418 0.47611452 0.51738715]
  [0.03865835 0.39629504 0.2088813  0.15414601]]]
[[1 1 0 1]
 [1 0 0 0]
 [0 0 0 0]]
[[0 2 0 1]
 [0 2 1 0]]


# Indexing Slicing and Iterating

In [65]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [53]:
a[2]

8

In [55]:
a[2:5]

array([ 8, 27, 64])

In [57]:
a[:6:2]

array([ 0,  8, 64])

In [59]:
a[:6:2] = -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [70]:
a[:-1]

array([  0,   1,   8,  27,  64, 125, 216, 343, 512])

In [71]:
a[::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

## Multidimensional

In [74]:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [75]:
b[2,3]

23

In [86]:
b[0:2]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [95]:
b[0:2,1]

array([ 1, 11])

In [96]:
b[:,2]

array([ 2, 12, 22, 32, 42])

In [97]:
b[-1]

array([40, 41, 42, 43])

## The dots (...) represent as many colons as needed to produce a complete indexing tuple. For example, if x is an array with 5 axes, then
```
x[1,2,...] is equivalent to x[1,2,:,:,:],
x[...,3] to x[:,:,:,:,3] and
x[4,...,5,:] to x[4,:,:,5,:].
```

In [98]:
a = np.floor(10*np.random.random((3,4)))
a

array([[8., 4., 0., 1.],
       [1., 5., 5., 4.],
       [9., 7., 1., 1.]])

In [99]:
a.shape

(3, 4)

In [100]:
a.reshape(4,3)

array([[8., 4., 0.],
       [1., 1., 5.],
       [5., 4., 9.],
       [7., 1., 1.]])

In [102]:
a.T

array([[8., 1., 9.],
       [4., 5., 7.],
       [0., 5., 1.],
       [1., 4., 1.]])

In [103]:
a.reshape(6,-1)

array([[8., 4.],
       [0., 1.],
       [1., 5.],
       [5., 4.],
       [9., 7.],
       [1., 1.]])

## [More NumPy Operation](https://docs.scipy.org/doc/numpy/user/quickstart.html)