In [1]:
import torch
from torch.autograd import Variable

x_data = torch.tensor([[1.0], [2.0], [3.0]])
y_data = torch.tensor([[2.0], [4.0], [6.0]])


class Model(torch.nn.Module):

    def __init__(self):
        """
        In the constructor we instantiate two nn.Linear module
        """
        super(Model, self).__init__()
        self.linear = torch.nn.Linear(1, 1)  # One in and one out, linear = y=wx + b

    def forward(self, x):
        """
        In the forward function we accept a Variable of input data and we must return
        a Variable of output data. We can use Modules defined in the constructor as
        well as arbitrary operators on Variables.
        """
        y_pred = self.linear(x)
        return y_pred



In [14]:
m = torch.nn.Linear(2, 1, bias=True)
print("weight=",m.weight)
print("bias=",m.bias)
input = torch.ones(1,2)
print("input=",type(input))
output = m(input)
print(output.size())
print(output)

weight= Parameter containing:
tensor([[-0.3798, -0.4963]], requires_grad=True)
bias= Parameter containing:
tensor([-0.6875], requires_grad=True)
input= <class 'torch.Tensor'>
torch.Size([1, 1])
tensor([[-1.5636]], grad_fn=<ThAddmmBackward>)


In [8]:
# our model
model = Model()


In [10]:
# Construct our loss function and an Optimizer. The call to model.parameters()
# in the SGD constructor will contain the learnable parameters of the two
# nn.Linear modules which are members of the model.
criterion = torch.nn.MSELoss(size_average=False)
# optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)



/home/joshhu/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))


In [11]:
# Training loop
for epoch in range(500):
        # Forward pass: Compute predicted y by passing x to the model
    y_pred = model(x_data)

    # Compute and print loss
    loss = criterion(y_pred, y_data)
    print(epoch, loss.data[0])

    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

/home/joshhu/anaconda3/envs/pytorch/lib/python3.6/site-packages/ipykernel/__main__.py:8: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number


0 tensor(100.0471)
1 tensor(45.2244)
2 tensor(20.8090)
3 tensor(9.9303)
4 tensor(5.0778)
5 tensor(2.9081)
6 tensor(1.9330)
7 tensor(1.4897)
8 tensor(1.2833)
9 tensor(1.1825)
10 tensor(1.1289)
11 tensor(1.0963)
12 tensor(1.0733)
13 tensor(1.0546)
14 tensor(1.0380)
15 tensor(1.0225)
16 tensor(1.0075)
17 tensor(0.9929)
18 tensor(0.9786)
19 tensor(0.9645)
20 tensor(0.9506)
21 tensor(0.9369)
22 tensor(0.9235)
23 tensor(0.9102)
24 tensor(0.8971)
25 tensor(0.8842)
26 tensor(0.8715)
27 tensor(0.8590)
28 tensor(0.8466)
29 tensor(0.8345)
30 tensor(0.8225)
31 tensor(0.8107)
32 tensor(0.7990)
33 tensor(0.7875)
34 tensor(0.7762)
35 tensor(0.7651)
36 tensor(0.7541)
37 tensor(0.7432)
38 tensor(0.7325)
39 tensor(0.7220)
40 tensor(0.7116)
41 tensor(0.7014)
42 tensor(0.6913)
43 tensor(0.6814)
44 tensor(0.6716)
45 tensor(0.6620)
46 tensor(0.6524)
47 tensor(0.6431)
48 tensor(0.6338)
49 tensor(0.6247)
50 tensor(0.6157)
51 tensor(0.6069)
52 tensor(0.5982)
53 tensor(0.5896)
54 tensor(0.5811)
55 tensor(0.5727

In [12]:
# After training
hour_var = torch.tensor([[4.0]])
y_pred = model(hour_var)
print("predict (after training)",  4, model(hour_var).data[0][0])

predict (after training) 4 tensor(7.9650)
